### PR TITLE
refresh-appearance

### PR DESCRIPTION
**Pull request by AlanGriffiths**
A bit of reworking of the confined snap using yambar

### CODE REVIEW

**Review by Saviq — COMMENTED** [review]
Not sure if by design, but the bar has some squares? Should those be icons?

obraz

Some errors from the cmdline:

```
 err: modules/network.c:196: failed to create netlink socket: Operation not permitted (1)
 err: bar/wayland.c:1473: seat0: failed to load cursor 'hand2'
 err: bar/bar.c:368: module: RIGHT #0 (net(wlp166s0)): non-zero exit value: 1
```

With two displays, there's no panel at all?

**Comment by AlanGriffiths** [comment]
Those squares should be characters from the awesome font:
```
$ find /snap/confined-shell/current/usr/share/fonts -name *awesome*
/snap/confined-shell/current/usr/share/fonts/opentype/font-awesome
/snap/confined-shell/current/usr/share/fonts/truetype/font-awesome
/snap/confined-shell/current/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf
```

Not sure why you're not seeing them

**Comment by Saviq** [comment]
> Not sure why you're not seeing them

Fonts are treated special on Classic, aren't they:

```
$ snap run --shell confined-shell
$ ls /usr/share/fonts/truetype
dejavu
```

**Comment by AlanGriffiths** [comment]
Is awsome missing in `$SNAP/usr/share/fonts/truetype`? (It should be staged by the yambar part)

And bind-mounted by:

```yaml
layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
```

**Comment by Saviq** [comment]
> Is awsome missing in `$SNAP/usr/share/fonts/truetype`? (It should be staged by the yambar part)

Nope, it's there:

```plain
michal@michal-laptop:~$ find /usr/share/fonts/truetype
/usr/share/fonts/truetype
/usr/share/fonts/truetype/dejavu
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
michal@michal-laptop:~$ find $SNAP/usr/share/fonts/truetype
/snap/confined-shell/199/usr/share/fonts/truetype
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
/snap/confined-shell/199/usr/share/fonts/truetype/font-awesome
/snap/confined-shell/199/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf
```

> And bind-mounted by:
> 
> ```yaml
> layout:
>   /usr/share/fonts:
>     bind: $SNAP/usr/share/fonts
> ```

It's as if SnapD mounts the dejavu font over the snap one?…

**Comment by AlanGriffiths** [comment]
> With two displays, there's no panel at all?

Hmm, that works fine outside the snap, hadn't tried it snapped.

**Comment by AlanGriffiths** [comment]
> It's as if SnapD mounts the dejavu font over the snap one?…

Maybe snapd has got its bind mounts in a twist (and didn't remount correctly after a previous install). Does remove/install workaround?

**Comment by Saviq** [comment]
The "lighter touch" worked indeed :+1:.

**Comment by AlanGriffiths** [comment]
> > With two displays, there's no panel at all?
> 
> Hmm, that works fine outside the snap, hadn't tried it snapped.

I can reproduce, but don't understand...

```plain
yambar: bar/wayland.c:1137: setup: Assertion `backend->monitor == NULL || backend->width / backend->monitor->scale <= backend->monitor->width_px' failed.
```

I've forced the same version of Mir (mir-team/dev) and yambar (1.9.0)  I'm using unsnapped in 23.04 without effect.

I've also found that the problem doesn't manifest with the x11 or Wayland backends.

**Comment by AlanGriffiths** [comment]
OK, so the problem doesn't lie in yambar itself, nor in Mir/Miriway: if, under the `confined-shell` desktop I run the snapped yambar in the 23.04 environment it works fine.

But using the `LD_LIBRARY_PATH` from the snapped (22.04) environment something goes wrong with the initialisation sequence.

I don't think this needs further investigation at this time.

**Review by Saviq — APPROVED** [review]
OK, let it be.

bors merge

**Pull request merged**
