### PR TITLE
snap: migrate to new graphics-core22

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Looks good

**Comment by Saviq** [comment]
> Looks good

Just needed to drop libdrm, done now.

**Review by AlanGriffiths — APPROVED** [review]
WFM

**Review by AlanGriffiths — APPROVED** [review]

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Pull request merged**
